version: "3.8"

services:
  balance-checker:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBANK_API_KEY=${DEBANK_API_KEY}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
